version: '3.8'

services:
  db:
    image: mysql@sha256:475221fcdc1c8972a9b2370f051d80488b49a9a972bf75a22903881b97afec3b
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
